spring:
  url: jdbc:mysql://localhost:3307/?allowPublicKeyRetrieval=true&useSSL=false
  user: root
  password: root
  default-schema: cinema_gateway
  jpa:
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3307/cinema_gateway?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root

server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org.hibernate.SQL: DEBUG