spring:
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3307/?allowPublicKeyRetrieval=true&useSSL=false
    user: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    default-schema: cinema_gateway

  datasource:
    url: jdbc:mysql://localhost:3307/cinema_gateway?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

