@startuml
title Possible operations on Repertoire
actor Igor #blue
control RepertoireController
autonumber
Igor -> RepertoireController: [POST]\ncreate repertoire
|||
Igor -> RepertoireController: [GET]\nget repertoires for\ngiven cinema
|||
Igor -> RepertoireController: [PATCH]\nset repertoire's \nnew date
@enduml