spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
server:
  error:
    include-message: always
  servlet:
    context-path: /cinema
springdoc:
  swagger-ui:
    path: /swagger.html


