# This is a basic workflow to help you get started with Actions

name: job_test

# Controls when the workflow will run
on: 
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
  
    paths:
    - "**.groovy"
    
    branches:  
      - "master" 
      - "cinema_api_1"
    
  pull_request:
    branches:  
      - "master" 
      - "cinema_api_1"
    
  workflow_dispatch:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle Wrapper
      run: ./gradlew build
